base_url = "https://sairam2661.github.io"
title = "Sairam"
description = "Graduate student at UC San Diego."

theme = "apollo"
compile_sass = true
build_search_index = true
generate_feeds = true
minify_html = false

taxonomies = [
    { name = "tags", feed = true },
]


[extra]
theme = "toggle"
use_cdn = false
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name= "/about", url= "/about", weight= 1 },
    { name= "/projects", url= "/projects", weight= 2 },
    { name= "/publications", url= "/pubs", weight= 3 },
]
stylesheets = ["custom.css"]

[[extra.socials]]
name = "github"
url = "https://github.com/sairam2661"
icon = "github"

[[extra.socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/sairamvaidya"
icon = "linkedin"

[[extra.socials]]
name = "email"
url = "mailto:smahadevaganapathy@ucsd.edu"
icon = "email"
